### ISSUE TITLE
aar to Maven Central

### ISSUE THREAD

**Issue by snowdream** [RomainPiel/Titanic#1]
@RomainPiel please publish aar to Maven Central,Thank You.

**Comment by ed-george** [comment]
+1 for this

**Comment by wasabeef** [comment]
:+1:

**Comment by aknkaplanoglu** [comment]
@RomainPiel please publish aar to Maven Central,Thank You.

**Comment by hmzuleta** [comment]
bump

**Comment by andersonbadari** [comment]
+1

**Comment by xtonousou** [comment]
+1

**Comment by romainpiel** [comment]
Hey guys, I'm sorry but I'm afraid it will not happen. This is more an experiment/blog post sample than a library. If you want this in your app, go check out the source it's fairly self explanatory: https://github.com/RomainPiel/Titanic/tree/master/library/src/main/java/com/romainpiel/titanic/library
