### ISSUE TITLE
how to set this to background of a view

### ISSUE THREAD

**Issue by Div-e-Sepid** [RomainPiel/Titanic#2]
I want to have this waves on an ImageView or on a background of a view.. Is there any way to accomplish this without using a textView!?

**Comment by joscandreu** [comment]
+1

**Comment by romainpiel** [comment]
It's actually pretty doable with a custom drawable:
- Take the code from `TitanicTextView` and move it to a new custom drawable class. (You might have to change a few overridden class to the appropriate ones)
- Move the animation related code (from `TitanicTextView`) to a custom image view
- Set the custom drawable to your custom image view
- Animate all the things!

Sorry I don't have time to spend on that but play with the code it's really not complicated.
